# Generated by Django 5.1.1 on 2024-10-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_bookseatdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('feed', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bookseatdata',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
