# Generated by Django 5.1.1 on 2024-10-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_feedbackdata_alter_bookseatdata_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbackdata',
            new_name='FeedbackOrContactData',
        ),
    ]
